version: 0.2

phases:
  pre_build:
    commands:
      # Log in to the Amazon ECR registry
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
      # Build the Docker image
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
