version: 0.2

phases:
  pre_build:
    commands:
      # Log in to Docker Hub
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
      # Build the Docker image
      - echo Building the Docker image...
      - docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .

      # Tag the image with 'latest'
      - docker tag $DOCKER_USERNAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $DOCKER_USERNAME/$IMAGE_NAME:latest

  post_build:
    commands:
      # Push the Docker image with the commit hash tag
      - echo Pushing the Docker image with commit hash tag...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

      # Push the Docker image with 'latest' tag
      - echo Pushing the Docker image with 'latest' tag...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

artifacts:
  files:
    - '**/*'
