stages:
  clean:
    cmd: python Sentiment_Analysis/clean.py data/raw/training.1600000.processed.noemoticon.csv
    deps:
    - Sentiment_Analysis/clean.py
    - data/raw
    params:
    - clean.lemmarize

  split:
    cmd: python Sentiment_Analysis/split.py data/interim/clean_dataset.csv
    deps:
    - Sentiment_Analysis/split.py
    - data/interim
    params:
    - split.train_size
    - split.val_size
    - split.test_size
    - split.random_state



