stages:

  train_lstm_model:
    cmd: python Sentiment_Analysis/lstm_training.py
    deps:
    - Sentiment_Analysis/lstm_training.py
    - data/processed/X_y_data_lstm.npz
    - data/processed/tokenizer.pickle
    - params.yaml
    outs:
    - models/optimized_lstm_final.keras
    params:
    - lstm_train
