data_preprocessing:
  track_emissions: False

lstm_train:
  track_emissions: False
  upload_experiment: True
  run_deepchecks: True
  max_vocab_size: 10000
  max_len: 80
  embedding_dim: 64
  lstm_units: 32
  batch_size: 256
  num_epochs: 10
  learning_rate: 0.001
  model_name: 'optimized_lstm'
  random_state: 42
  test_size: 0.3
